# Generated by Django 3.2.6 on 2021-09-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Медиа файл', 'verbose_name_plural': 'Медиа файлы'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
