# Generated by Django 3.2.6 on 2021-09-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210921_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediaFiles', to='posts.post'),
        ),
    ]
