# Generated by Django 3.2.5 on 2021-07-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(max_length=254, null=True, verbose_name='О себе'),
        ),
    ]
