# Generated by Django 3.2.6 on 2021-10-06 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendlist',
            options={'verbose_name': 'Friend', 'verbose_name_plural': 'Friends'},
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
