# Generated by Django 3.2.5 on 2021-07-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='login'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
